name: golangci-lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/github-workflows
  pull_request:

permissions:
  contents: read
  issues: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          github-token: ${{ secrets.BZE_LINT_ISSUES_TOKEN }}
          args: --timeout=30m
          only-new-issues: true
